== Installation

=== Cloning the Repository
Users can obtain the source code by

[source, bash]
----
git clone https://github.com/matt-frey/epic.git
----

It is however recommended to use the latest link:https://github.com/matt-frey/epic/releases[release] for production runs. EPIC contributors can also clone the repository using the SSH version
[source, bash]
----
git clone git@github.com:matt-frey/epic.git
----


=== Prerequisites
EPIC is implemented in Fortran; hence, a Fortran compiler is required. We recommend to use link:https://gcc.gnu.org/wiki/GFortran[GNU Fortran compiler]. It further depends on link:https://www.hdfgroup.org/solutions/hdf5/[HDF5] and
link:https://www.unidata.ucar.edu/software/netcdf/[NetCDF]. Scripts to install HDF5 and NetCDF are found in the
source code subdirectory `dependencies`. No guarantee can be given for a successful installation with these scripts.
Optionally, users can install Python in order to use the provided pre- and post-processing scripts.

=== Configuring
In this subsection `$PREFIX` denotes the installation directory of EPIC. The basic installation is obtained by typing
[source, bash]
----
$ autoreconf --install
$ mkdir build
$ cd build
$ ../configure --prefix=$PREFIX
$ make
$ make install
----
in your terminal.

**Note:** You can add the bin directory `$PREFIX/bin` to your `$PATH` and `PYTHONPATH` environment variables with
[source, bash]
----
export PATH=$PREFIX/bin:$PATH
export PYTHONPATH=$PREFIX/bin:$PYTHONPATH
----
