AM_FCFLAGS = -I $(top_builddir)/src/mpi \
             -I $(top_builddir)/src/utils

lib_LTLIBRARIES = libepic_parcel_types.la
libepic_parcel_types_la_SOURCES = 	\
	../utils/datatypes.f90		\
	../utils/armanip.f90		\
	splines.f90      		\
	parcel_container.f90		\
	parcel_ellipsoid.f90		\
	parcel_types.f90		
